version: '3.8'
services:
  postgres:
    image: postgres
    container_name: server_db # can be changed to the name of your api
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
    - app
  server-dev:
    container_name: server_dev
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000 # should point to your assigned port
    env_file:
      - .env
    working_dir: /app
    networks:
      - app
    depends_on:
      - postgres # name of service it depends on
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks:
  app: