name: Deploy to Staging

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Deploy App Engine
        id: deploy
        uses: 'google-github-actions/deploy-appengine@main'
        with:
          service_account:  ${{ secrets.GCP_SA_KEY }}
          gae_config_path: './app.yaml'