name: PR

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - run: npm test
